dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      classic: true
      channel: latest/beta

matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.0.0
      solution: ./SuperBack/SuperBack.sln
      sudo: required
      script:
        - sudo snap alias dotnet-sdk.dotnet dotnet
        - dotnet restore
        - dotnet build --configuration Debug
        - dotnet test
        - dotnet build --configuration Release


