dist: trusty
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: latest/beta
  sonarcloud:
    organization: "ometeo"
    token:
      secure: travis encrypt d3e89d7fbd0742be6e60472a214beffe580acde1

matrix:
  include:
    - language: csharp
      mono: none
      solution: ./SuperBack/SuperBack.sln
      sudo: required
      script:
        - sudo snap alias dotnet-sdk.dotnet dotnet
        - cd SuperBack
        - dotnet restore
        - dotnet build --configuration Debug
        - dotnet test
        - dotnet build --configuration Release
        - sonar-scanner


